In [1]:
# recommendation systems

In [4]:
import pandas as pd # pandas package
movies = pd.DataFrame({ # pd.DataFrame({}) where we create our own dataset via DataFrame
    'title':['Interstellar','Inception','The Matrix','The Martian','Gravity'], # movie titles
    'description': ['Explorers attempt to save humanity by going through wormhole',
                    'Thief steals corporate secrets to erase his past',
                    'Hacker learns reality and fights against computers',
                    'Astronaut lives in Mars',
                    'Astronauts try to survive after fatal accident'], # movie descriptions
})
movies # showcase the DataFrame

          title                                        description
0  Interstellar  Explorers attempt to save humanity by going th...
1     Inception   Thief steals corporate secrets to erase his past
2    The Matrix  Hacker learns reality and fights against compu...
3   The Martian                            Astronaut lives in Mars
4       Gravity     Astronauts try to survive after fatal accident

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer # TfidVectorizer package
vectorizer = TfidfVectorizer(stop_words='english') # variable that converts english text descriptions into TF-IDF vectors
tfidf_matrix = vectorizer.fit_transform(movies['description']) # matrix that builds the vocabulary table of all english text words
tfidf_matrix # shows tfidf_matrix

# outcome is 5 rows by 39 columns (since each word is a vector)

<5x25 sparse matrix of type '<class 'numpy.float64'>'
	with 25 stored elements in Compressed Sparse Row format>

In [17]:
from sklearn.metrics.pairwise import cosine_similarity # cosine similarity package

similarity_matrix = cosine_similarity(tfidf_matrix,tfidf_matrix) # uhh not sure!

similarity_matrix # shows similarity matrix

# outcome is a binary table

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
movie = 'The Matrix' # variable holds string 'Interstellar'
idx = movies[movies['title']==movie].index[0] # i'm not sure what this does

for i, title in enumerate(movies['title']): # checks for title in the title column in movies dataframe
    print(f"{title:12s} similarity = {similarity_matrix[idx,i]: .4f}") # where for every 12 seconds, check if the the idx

Interstellar similarity =  0.0000
Inception    similarity =  0.0000
The Matrix   similarity =  1.0000
The Martian  similarity =  0.0000
Gravity      similarity =  0.0000

In [34]:
# user-based collaborative filtering
import numpy as np # numpy package
ratings = pd.DataFrame( # ratings DataFrame
    {
    'Interstellar': [5,4,np.nan,5],
    'Inception': [4,5,2,5],
    'The Matrix': [1,2,5,np.nan],
    'The Martian': [5,5,2,4],
    'Gravity': [4,3,np.nan,4]  
    },
    index=['User A','User B','User C','User D'] # rows that contain rating information
)
ratings

        Interstellar  Inception  The Matrix  The Martian  Gravity
User A           5.0          4         1.0            5      4.0
User B           4.0          5         2.0            5      3.0
User C           NaN          2         5.0            2      NaN
User D           5.0          5         NaN            4      4.0

In [39]:
ratings_filled = ratings.fillna(0) # something to use in the future to fill NaN with system average or 0s
ratings

        Interstellar  Inception  The Matrix  The Martian  Gravity
User A           5.0          4         1.0            5      4.0
User B           4.0          5         2.0            5      3.0
User C           NaN          2         5.0            2      NaN
User D           5.0          5         NaN            4      4.0

In [40]:
similarity = cosine_similarity(ratings_filled) # apply cosine_similarity on ratings_filled df

similarity_df = pd.DataFrame(similarity, index=ratings.index, columns=ratings.index) # have spaces cuz that.. corrected that
# 

similarity_df # shows table

          User A    User B    User C    User D
User A  1.000000  0.975606  0.439473  0.981836
User B  0.975606  1.000000  0.587558  0.956688
User C  0.439473  0.587558  1.000000  0.346026
User D  0.981836  0.956688  0.346026  1.000000

In [45]:
sims=similarity_df['User C'].drop('User C') # idk 
ratings_other=ratings['Interstellar'].drop('User C') # idk
# mask=ratings_other.notna()
result = np.sum(sims*ratings_other)/np.sum(abs(sims)) # calculation for the weighted average
result # show result

np.float64(4.572080254259292)

In [47]:
def predict_rating(UserName,movieName): # same thing as above but in function
    sims=similarity_df[UserName].drop(UserName) # idk 
    ratings_other=ratings[movieName].drop(UserName) # idk
    result = np.sum(sims*ratings_other)/np.sum(abs(sims)) 
    return result

In [56]:
output = predict_rating('User D','Gravity') # calling function with parameters AND CASE SENSITIVE
output # print output

np.float64(2.975381807269802)